/**
 * Project: Anime — "Codex prose": rich, hand-authored item descriptions in the system's own
 * voice. The GM writes a description in a plain textarea using light markup (headings, dividers,
 * lists, bold **Labels**, and the outcome blocks the system actually uses — Hit / Miss / Contest /
 * Threshold / Wound) and it renders as a formatted card that fills the View tab and the chat card.
 * Inline styling lives in `styleManualRules` (numbers auto-blue, `backtick` blue, ~tilde~ gold,
 * Foundry [[rolls]]/@links preserved). NOT a copy of any other system — the block vocabulary maps
 * to Project: Anime's V2 rules.
 *
 * Legacy descriptions were stored as HTML (ProseMirror). Those are detected and passed straight
 * through untouched (backward-compatible); `htmlToMarkup` converts them to editable markup when the
 * GM opens the editor. Everything here is pure/sync except the enriched wrapper and the localized
 * outcome inserts. No Foundry globals are touched at module scope.
 */
import {
  techniqueDie, contestTarget, skillDieSpecs, actorTalents, rangeLabel, physicalRangeLabel,
  modifierTakes, skillTarget, skillDuration, modifierValue, rangeHasTiles, getTalent
} from "./config.mjs";

/** Outcome labels the system uses (rules doc V2) → the color role their bold label wears.
 *  Anything not listed renders as a neutral stat label (Range / Target / Energy / …). */
const OUTCOME_CLASS = {
  hit: "pa-out-hit", miss: "pa-out-miss",
  contest: "pa-out-contest", contested: "pa-out-contest", won: "pa-out-hit", win: "pa-out-hit",
  lost: "pa-out-miss", lose: "pa-out-miss", fail: "pa-out-miss", failure: "pa-out-miss",
  tie: "pa-out-neutral",
  threshold: "pa-out-threshold",
  wound: "pa-out-wound", wounded: "pa-out-wound"
};

/** A description already holds block HTML (a legacy ProseMirror value) — render it as-is. */
export function isLegacyHTML(raw) {
  return /<(p|div|ul|ol|h[1-6]|hr|table|blockquote|section)\b/i.test(String(raw ?? ""));
}

const numSpan = (v) => `<span class="pa-rules-num">${v}</span>`;
const impSpan = (v) => `<span class="pa-rules-improve">${v}</span>`;

/** Inline-style one line of prose markup: HTML-escapes the text, then **bold**, `blue`, ~gold~,
 *  and bare numbers → styled spans (preserving [[rolls]] / @links for a later enrich pass).
 *  Sync. All emitted tags are ours, so a literal "<x>" in the input renders as text. */
export function styleManualRules(raw) {
  let s = String(raw ?? "");
  if (!s.trim()) return "";
  // Escape the author's literal text FIRST, so a stray "<x>" renders as text instead of being
  // swallowed as an unknown tag. Every tag emitted below is generated by us, never from the input.
  s = s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  // Stashed fragments hide behind a fake `<pakeep N>` tag: the number-colorize pass skips it as
  // an HTML tag, so its index digits are never mistaken for a rules number.
  const stash = [];
  const keep = (html) => `<pakeep ${stash.push(html) - 1}>`;
  // Preserve Foundry enricher tokens so their inner numbers aren't colorized/split.
  s = s.replace(/\[\[[^\]]*\]\](?:\{[^}]*\})?/g, (m) => keep(m));
  s = s.replace(/@\w+\[[^\]]*\](?:\{[^}]*\})?/g, (m) => keep(m));
  // Manual highlights: `blue` and ~gold~ (button-inserted or typed).
  s = s.replace(/~([^~\n]+)~/g, (_m, t) => keep(impSpan(t)));
  s = s.replace(/`([^`\n]+)`/g, (_m, t) => keep(numSpan(t)));
  // Inline bold: **text** -> <strong> (numbers inside still color, since it's stashed whole).
  s = s.replace(/\*\*(\S[\s\S]*?)\*\*/g, (_m, t) => keep(`<strong>${t}</strong>`));
  // Auto-blue the bare numbers that remain; an HTML tag (incl. the sentinel) passes through.
  s = s.replace(/<[^>]+>|(\bd\d+\b|[+\-−]?\d+%?)/g, (m, num) => (num ? numSpan(num) : m));
  // Restore stashed fragments; loop so a token nested inside a highlight also resolves.
  for (let pass = 0; pass <= stash.length && s.includes("<pakeep "); pass++) {
    s = s.replace(/<pakeep (\d+)>/g, (_m, i) => stash[Number(i)] ?? "");
  }
  return s;
}

/** Inline pass for one line of text: the shared styler escapes it, then applies **bold**,
 *  `blue`, ~gold~, auto-blue numbers, and preserves [[rolls]] / @links. */
function inline(text) {
  const t = String(text ?? "");
  return t.trim() ? styleManualRules(t) : "";
}

/** Render the light markup of a description into the `.pa-desc-prose` block. Sync + pure. */
export function renderProse(raw) {
  const src = String(raw ?? "").replace(/\r\n?/g, "\n");
  if (!src.trim()) return "";

  const out = [];
  let para = [];            // buffered lines of the current paragraph
  let list = null;          // { tag: "ul"|"ol", items: [] }
  const flushPara = () => { if (para.length) { out.push(`<p>${para.join("<br>")}</p>`); para = []; } };
  const flushList = () => {
    if (list) { out.push(`<${list.tag} class="pa-desc-list">${list.items.map((i) => `<li>${i}</li>`).join("")}</${list.tag}>`); list = null; }
  };
  const flushAll = () => { flushPara(); flushList(); };

  for (const rawLine of src.split("\n")) {
    const line = rawLine.trim();

    // Blank line — end the current paragraph/list.
    if (!line) { flushAll(); continue; }

    // Divider: a line of --- / *** / ___ .
    if (/^([-*_])\1{2,}$/.test(line)) { flushAll(); out.push('<hr class="pa-desc-hr">'); continue; }

    // Heading: # / ## / ### text .
    let m = /^#{1,3}\s+(.*)$/.exec(line);
    if (m) { flushAll(); out.push(`<div class="pa-desc-h">${inline(m[1])}</div>`); continue; }

    // Bullet / numbered list item (bullet requires the space so "**Hit**" isn't caught).
    m = /^[-*]\s+(.*)$/.exec(line);
    if (m) { flushPara(); if (!list || list.tag !== "ul") { flushList(); list = { tag: "ul", items: [] }; } list.items.push(inline(m[1])); continue; }
    m = /^\d+\.\s+(.*)$/.exec(line);
    if (m) { flushPara(); if (!list || list.tag !== "ol") { flushList(); list = { tag: "ol", items: [] }; } list.items.push(inline(m[1])); continue; }

    // Outcome line: only a leading **Hit** / **Miss** / **Contest** / **Threshold** / **Wound**
    // (letters compared, so "**Hit:**" still matches) starts a colored outcome block. Any OTHER
    // leading bold — a stat label, or a sentence that merely opens with emphasis — falls through to
    // a normal paragraph where inline() bolds it, so ordinary prose isn't hijacked into a label row.
    m = /^\*\*([^*]+)\*\*\s*([\s\S]*)$/.exec(line);
    if (m) {
      const cls = OUTCOME_CLASS[m[1].toLowerCase().replace(/[^a-z]/g, "")];
      if (cls) {
        flushAll();
        const rest = m[2] ? ` ${inline(m[2])}` : "";
        out.push(`<p class="pa-desc-line"><strong class="${cls}">${inline(m[1])}</strong>${rest}</p>`);
        continue;
      }
    }

    // Plain text — accumulate into the current paragraph (single newline → soft break).
    flushList();
    para.push(inline(line));
  }
  flushAll();
  return out.length ? `<div class="pa-desc-prose">${out.join("")}</div>` : "";
}

/** The display HTML for an item's description: legacy HTML passes through; markup is rendered.
 *  "" when blank. Async only for the Foundry enrich pass (resolves @links / [[rolls]]). */
export async function renderDescriptionHTML(item, { secrets = false } = {}) {
  const raw = (item?.system?.description ?? "").trim();
  if (!raw) return "";
  const body = isLegacyHTML(raw) ? raw : renderProse(raw);
  const TE = foundry.applications?.ux?.TextEditor?.implementation ?? globalThis.TextEditor;
  return TE.enrichHTML(body, { relativeTo: item, secrets, rollData: item?.getRollData?.() ?? {} });
}

/** Sync description block (no Foundry enrich) — for render paths that build HTML synchronously,
 *  like the actor-sheet command-row dropdown. Inline calc tokens still resolve (the resolver is
 *  sync); only Foundry's own @links / [[rolls]] stay literal here. "" when blank. */
export function renderDescriptionBlock(item) {
  const raw = (item?.system?.description ?? "").trim();
  if (!raw) return "";
  return resolveInlineCalcs(isLegacyHTML(raw) ? raw : renderProse(raw), item);
}

/* -------------------------------------------- */
/*  Inline autocalc tokens                      */
/* -------------------------------------------- */

/** The inline autocalc vocabulary: `@talent[Name]` plus the bare value tokens. Every render
 *  re-resolves them against the owning item/actor, so descriptions never go stale. The same
 *  pattern backs the registered Foundry enricher (helpers/enrichers.mjs) and the sync resolver
 *  below — keep them identical. */
export const INLINE_CALC_SOURCE = "@(talent|contest|threshold|damage|energy|range|target|duration|modifier|effect|rule|attack|trigger|status|scale)\\b(?:\\[([^\\]]*)\\])?";

/** A resolved token: just the blue value span — the token says exactly what it computes;
 *  authors write their own labels around it. */
const calcSpan = (value, tooltip) => {
  const esc = foundry.utils.escapeHTML;
  return `<span class="pa-rules-num pa-inline-calc" data-tooltip="${esc(tooltip)}">${esc(String(value))}</span>`;
};
/** A rules-term reference (@modifier[X] / @effect[X]): the canonical label, dotted-underlined,
 *  with the printed rules text riding as its hover tooltip. */
const refSpan = (label, desc) => {
  const esc = foundry.utils.escapeHTML;
  return `<span class="pa-rules-num pa-calc-ref" data-tooltip="${esc(desc)}">${esc(label)}</span>`;
};
const unlinkedSpan = (raw) => {
  const esc = foundry.utils.escapeHTML;
  return `<span class="pa-calc-unlinked" data-tooltip="${esc(game.i18n.localize("PROJECTANIME.Prose.calcUnlinked"))}">${esc(raw)}</span>`;
};

/**
 * One inline calc token → its rendered span (an HTML string). `doc` is the resolution context
 * (an Item, an Actor, or null); anything unresolvable — wrong item type, unknown Talent, no
 * context at all — degrades to the literal token in the muted "unlinked" style. Never throws.
 * Sync + shared by the async enricher and the sync block renderer.
 */
export function inlineCalcHTML(kind, arg, doc, raw) {
  const L = (k) => game.i18n.localize(k);
  try {
    const item = doc?.documentName === "Item" ? doc : null;
    const actor = doc?.documentName === "Actor" ? doc : item?.actor ?? null;
    const sys = item?.system;
    switch (kind) {
      case "talent": {
        const name = String(arg ?? "").trim().toLowerCase();
        const t = name && actor
          ? actorTalents(actor).find((x) => (x.name ?? "").trim().toLowerCase() === name) : null;
        if (t) return calcSpan(`${t.name} d${t.die}`, L("PROJECTANIME.Prose.calcTalent"));
        break;
      }
      case "contest": {
        if (item?.type !== "skill") break;
        const { die, hasTalent } = techniqueDie(item);
        return calcSpan(contestTarget(die, hasTalent), L("PROJECTANIME.Prose.calcContest"));
      }
      case "scale": {
        // The Technique's die/2 scaling value (rules: "When a Modifier uses die/2"):
        // Talent die/2 + 1 Trained Edge when Talent-built, else primary Attribute die/2. Min 1.
        if (item?.type !== "skill") break;
        const { die, hasTalent } = techniqueDie(item);
        return calcSpan(Math.max(1, Math.floor(die / 2) + (hasTalent ? 1 : 0)), L("PROJECTANIME.Prose.calcScale"));
      }
      case "threshold": {
        if (item?.type !== "weapon" && item?.type !== "shield") break;
        return calcSpan(Number(sys.threshold) || 0, L("PROJECTANIME.Prose.calcThreshold"));
      }
      case "damage": {
        if (item?.type === "weapon" || item?.type === "shield")
          return calcSpan(Number(sys.damage?.value) || 0, L("PROJECTANIME.Prose.calcDamage"));
        if (item?.type === "skill" && skillDieSpecs(sys).some((ds) => ds.effect === "strike")) {
          // Weapon-range Strikes deal the weapon's Damage; any other range marks 1 box.
          // Potent adds its bonus per take — mirror the damage engine (dice.mjs).
          const potent = (sys.modifiers ?? []).includes("potent")
            ? (CONFIG.PROJECTANIME?.potentBonus ?? 1) * modifierTakes("potent", sys) : 0;
          return sys.range?.scope === "weapon"
            ? calcSpan(potent ? `${L("PROJECTANIME.Prose.calcWeaponDamage")} + ${potent}` : L("PROJECTANIME.Prose.calcWeaponDamage"),
              L("PROJECTANIME.Prose.calcDamage"))
            : calcSpan(1 + potent, L("PROJECTANIME.Prose.calcDamage"));
        }
        break;
      }
      case "energy": {
        if (item?.type !== "skill") break;
        const passive = sys.actionType === "passive" || sys.effect === "companion";
        return passive
          ? calcSpan(Number(sys.passiveEnergyTax) || 0, L("PROJECTANIME.Prose.calcLock"))
          : calcSpan(Number(sys.energyCost) || 0, L("PROJECTANIME.Prose.calcEnergy"));
      }
      case "range": {
        if (item?.type === "skill") {
          // A Weapon-range Technique reaches as far as the EQUIPPED weapon (main-hand
          // preferred — mirrors dice.mjs skillWeapon); no weapon equipped → the scope word.
          if (sys.range?.scope === "weapon") {
            const weapons = (actor?.items ?? []).filter((i) => i.type === "weapon" && i.system?.equipped);
            const w = weapons.find((x) => x.system.hand === "main") ?? weapons[0] ?? null;
            return calcSpan(w
              ? `${physicalRangeLabel(w.system.range)} ${L("PROJECTANIME.Skill.tiles")}`
              : rangeLabel(sys.range), L("PROJECTANIME.Prose.calcRange"));
          }
          return calcSpan(rangeHasTiles(sys.range?.scope)
            ? `${sys.range?.tiles ?? 0} ${L("PROJECTANIME.Skill.tiles")}`
            : rangeLabel(sys.range), L("PROJECTANIME.Prose.calcRange"));
        }
        if (item?.type === "weapon" || item?.type === "shield")
          return calcSpan(`${physicalRangeLabel(sys.range)} ${L("PROJECTANIME.Skill.tiles")}`, L("PROJECTANIME.Prose.calcRange"));
        break;
      }
      case "target": {
        if (item?.type !== "skill") break;
        // The Target plus its shaping Modifiers: Aura/Burst carry their die-scaled radius,
        // Chain its die-scaled leap count, Line/Mass their printed shape.
        const cfg = CONFIG.PROJECTANIME;
        const mods = sys.modifiers ?? [];
        const parts = [L(cfg.skillTargets[skillTarget(sys)])];
        for (const key of ["aura", "burst", "line", "mass", "chain"]) {
          if (!mods.includes(key)) continue;
          const label = L(cfg.skillModifiers[key] ?? key);
          if (key in (cfg.scaledModifiers ?? {})) parts.push(`${label} ${modifierValue(item, key)} ${L(cfg.scaledModifiers[key].unit)}`);
          else parts.push(label);
        }
        return calcSpan(parts.join(" · "), L("PROJECTANIME.Prose.calcTarget"));
      }
      case "modifier":
      case "effect": {
        // A rules-term reference — needs no item at all: matched (case-insensitively) against
        // the printed labels (or stored keys) of the V2 Modifier / Effect tables; hovering
        // shows what the term does.
        const cfgR = CONFIG.PROJECTANIME;
        const table = kind === "modifier" ? cfgR.skillModifiers : cfgR.skillEffects;
        const q = String(arg ?? "").trim().toLowerCase();
        if (!q) break;
        const hit = Object.entries(table ?? {}).find(([k, lab]) =>
          k.toLowerCase() === q || L(lab).trim().toLowerCase() === q);
        if (!hit) break;
        const descKey = kind === "modifier"
          ? `PROJECTANIME.Skill.modifierDesc.${hit[0]}` : `PROJECTANIME.Skill.effectDesc.${hit[0]}`;
        return refSpan(L(hit[1]), L(descKey));
      }
      case "trigger": {
        // A React Technique's Trigger ("Enters").
        if (item?.type !== "skill" || sys.actionType !== "react") break;
        const trig = CONFIG.PROJECTANIME.triggers?.[sys.trigger];
        if (!trig) break;
        return calcSpan(L(trig), L("PROJECTANIME.Prose.calcTrigger"));
      }
      case "attack": {
        // The item's ACTUAL roll dice — "Charm (d8) + Army Training (d6)": the Paired
        // Attribute + the bound Talent when one applies, else the two-Attribute pair.
        // Dice sizes come from the owning actor; unowned items show the names alone.
        if (!item) break;
        const cfgA = CONFIG.PROJECTANIME;
        const aName = (k) => L(cfgA.attributes[k] ?? k);
        const aDie = (k) => Number(actor?.system?.attributes?.[k]?.value) || 0;
        const piece = (name, die) => (die ? `${name} (d${die})` : name);
        let parts = null;
        if (item.type === "skill") {
          const t = getTalent(actor, sys.talentId);
          if (t) parts = [piece(aName(t.attribute), aDie(t.attribute)), piece(t.name, t.die)];
          else if (sys.attributes?.attrA && sys.attributes?.attrB) {
            parts = [piece(aName(sys.attributes.attrA), aDie(sys.attributes.attrA)),
              piece(aName(sys.attributes.attrB), aDie(sys.attributes.attrB))];
          }
        } else if (item.type === "weapon" || item.type === "shield") {
          const acc = sys.accuracy ?? {};
          const t = getTalent(actor, sys.talentId);
          if (acc.attrA) {
            parts = t
              ? [piece(aName(acc.attrA), aDie(acc.attrA)), piece(t.name, t.die)]
              : [piece(aName(acc.attrA), aDie(acc.attrA)), ...(acc.attrB ? [piece(aName(acc.attrB), aDie(acc.attrB))] : [])];
          }
        }
        if (!parts) break;
        return calcSpan(parts.join(" + "), L("PROJECTANIME.Prose.calcAttack"));
      }
      case "status": {
        // A Status condition reference — hover shows what it does. Needs no item; matched by
        // stored id or display name ("Lingering"/"decay", "Sealed"/"exhausted"), plus the
        // printed adjective "Cursed".
        const q = String(arg ?? "").trim().toLowerCase();
        if (!q) break;
        const want = q === "cursed" ? "curse" : q;
        const c = (CONFIG.PROJECTANIME.statusConditions ?? []).find((x) =>
          x.id.toLowerCase() === want || L(x.name).trim().toLowerCase() === want);
        if (!c) break;
        return refSpan(L(c.name), L(`PROJECTANIME.Status.desc.${c.id}`));
      }
      case "rule": {
        // A DICE-mechanic reference (Attack / Check / Test / Contest / Threshold / Trained
        // Edge / Luck / Combo / Fumble) — hover shows the V2 rule. Needs no item; matched by
        // key or printed label, case-insensitively.
        const q = String(arg ?? "").trim().toLowerCase();
        if (!q) break;
        const keys = ["attack", "check", "test", "contest", "threshold", "trainedEdge", "luck", "combo", "fumble"];
        const key = keys.find((k) =>
          k.toLowerCase() === q || L(`PROJECTANIME.Prose.rule.${k}`).trim().toLowerCase() === q);
        if (!key) break;
        return refSpan(L(`PROJECTANIME.Prose.rule.${key}`), L(`PROJECTANIME.Prose.ruleDesc.${key}`));
      }
      case "duration": {
        if (item?.type !== "skill") break;
        // The EFFECTIVE Duration — a Channeled/Scene Modifier or a Scene-by-rule Effect wins
        // over the stored field; Standard shows only its turn count (printed default 2).
        const cfgD = CONFIG.PROJECTANIME;
        const key = skillDuration(sys);
        return calcSpan(key === "standard"
          ? `${sys.effectDuration ?? cfgD.standardDurationTurns} ${L("PROJECTANIME.Skill.turns")}`
          : L(cfgD.skillDurations[key] ?? ""), L("PROJECTANIME.Prose.calcDuration"));
      }
    }
  } catch (_e) { /* degrade below — a token must never break a render */ }
  return unlinkedSpan(raw);
}

/** Replace every inline calc token in an HTML string with its freshly-resolved span. Skips
 *  HTML tags so attribute text is never rewritten (tokens live in text content only). Sync —
 *  used by `renderDescriptionBlock`; the async enrich path resolves the same tokens through
 *  the registered Foundry enricher instead. Because this path reads HTML SOURCE (the styler
 *  entity-escapes author text first) while the enricher reads DOM-decoded text nodes, entities
 *  are decoded here so both paths hand the resolver the same argument (`&amp;` last, so
 *  escape-produced strings round-trip). */
const decodeEntities = (t) => String(t)
  .replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, "&");
export function resolveInlineCalcs(html, item) {
  const s = String(html ?? "");
  if (!s.includes("@")) return s;
  const re = new RegExp(`<[^>]+>|${INLINE_CALC_SOURCE}`, "g");
  return s.replace(re, (m, kind, arg) =>
    (kind ? inlineCalcHTML(kind, arg == null ? arg : decodeEntities(arg), item, decodeEntities(m)) : m));
}

/** The outcome insert for a Hit / Contest / Threshold button, or null when the item gives the
 *  tool nothing to calculate (the plain prefix is used instead). Since v0.5.19 these insert
 *  LIVE TOKENS (`@threshold`, `@contest`, `@damage`) instead of frozen numbers — the values
 *  re-resolve on every render. `item` may be a real Item or a lightweight { type, system,
 *  actor } stand-in (the Skill Builder's draft). */
function outcomeInsert(tool, item) {
  const sys = item?.system;
  if (!sys) return null;
  const type = item.type;
  if (tool === "threshold" && (type === "weapon" || type === "shield")) return "**Threshold** @threshold ";
  if (tool === "contest" && type === "skill") return "**Contest** @contest ";
  if (tool === "hit") {
    if (type === "weapon" || type === "shield") {
      return `**Hit** ${game.i18n.format("PROJECTANIME.Prose.insDealDamage", { n: "@damage" })} `;
    }
    if (type === "skill" && skillDieSpecs(sys).some((ds) => ds.effect === "strike")) {
      // Weapon-range Strikes deal the weapon's Damage (a full phrase, no number to live-calc);
      // any other range marks boxes — @damage resolves the count (rules: Technique Damage).
      return sys.range?.scope === "weapon"
        ? `**Hit** ${game.i18n.localize("PROJECTANIME.Prose.insWeaponDamage")} `
        : `**Hit** ${game.i18n.format("PROJECTANIME.Prose.insDealDamage", { n: "@damage" })} `;
    }
  }
  return null;
}

/** Toolbar insert: given a textarea value + selection and a tool, return the new value. Shared by
 *  every authoring surface (item sheet, Skill Builder). Pass the item (or a { type, system, actor }
 *  stand-in) so the Hit / Contest / Threshold buttons insert their live tokens only where they can
 *  resolve. The Talent tool takes `arg` (a Talent name from the toolbar picker) and drops
 *  `@talent[Name]` at the caret. Unknown tool → no-op. */
const PROSE_WRAP = { highlight: "`", gold: "~", bold: "**" };
const PROSE_PREFIX = { heading: "# ", list: "- ", label: "**Label** ", hit: "**Hit** ", miss: "**Miss** ", contest: "**Contest** ", threshold: "**Threshold** " };
export function applyProseTool(value, selStart, selEnd, tool, item = null, arg = null) {
  const v = String(value ?? "");
  const s = Number.isFinite(selStart) ? selStart : v.length;
  const e = Number.isFinite(selEnd) ? selEnd : v.length;
  if (PROSE_WRAP[tool] != null) { const w = PROSE_WRAP[tool]; return v.slice(0, s) + w + v.slice(s, e) + w + v.slice(e); }
  if (tool === "talent") {
    const name = String(arg ?? "").replace(/[\[\]\n]/g, "").trim();
    return v.slice(0, s) + `@talent[${name}] ` + v.slice(e);
  }
  const prefix = (item && outcomeInsert(tool, item)) ?? PROSE_PREFIX[tool];
  if (prefix != null) { const ls = v.lastIndexOf("\n", s - 1) + 1; return v.slice(0, ls) + prefix + v.slice(ls); }
  if (tool === "divider") { const pad = s > 0 && v[s - 1] !== "\n" ? "\n" : ""; return v.slice(0, s) + `${pad}---\n` + v.slice(e); }
  return v;
}

/** Turn a legacy HTML description into editable markup so the textarea editor shows clean source
 *  instead of raw tags. One-way + lossy by design (good enough to hand-edit). "" when blank. */
export function htmlToMarkup(html) {
  let s = String(html ?? "");
  if (!s.trim()) return "";
  // Only convert when the value actually contains an HTML tag; bare "<word>" in prose is kept as-is.
  if (!/<\/?(strong|em|b|i|u|br|span|a|p|div|ul|ol|li|h[1-6]|hr|table|thead|tbody|tr|td|th|blockquote|section|img|code|pre)\b/i.test(s)) return s.trim();
  return s
    .replace(/<\s*(h[1-6])[^>]*>([\s\S]*?)<\s*\/\s*\1\s*>/gi, (_m, _h, t) => `\n# ${t}\n`)
    .replace(/<\s*hr\s*\/?>/gi, "\n---\n")
    .replace(/<\s*li[^>]*>([\s\S]*?)<\s*\/\s*li\s*>/gi, (_m, t) => `\n- ${t}`)
    .replace(/<\s*\/?\s*(ul|ol)[^>]*>/gi, "\n")
    .replace(/<\s*(strong|b)\s*>([\s\S]*?)<\s*\/\s*\1\s*>/gi, (_m, _t, t) => `**${t}**`)
    .replace(/<\s*br\s*\/?>/gi, "\n")
    .replace(/<\s*\/\s*(p|div)\s*>/gi, "\n\n")
    .replace(/<\s*(p|div)[^>]*>/gi, "")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'")
    .replace(/[ \t]+\n/g, "\n").replace(/\n{3,}/g, "\n\n")
    .trim();
}
